<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HRM\SalaryStructure;
use Illuminate\Support\Str;

class SalaryStructureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Sri Lanka Hospital Salary Structures
     */
    public function run(): void
    {
        $structures = [
            [
                'grade_code' => 'G1',
                'title' => 'Executive / Manager',
                'description' => 'Hospital Directors, Department Heads, Senior Management',
                'min_salary' => 150000,
                'max_salary' => 250000,
                'medical_allowance' => 15000,
                'transport_allowance' => 10000,
                'housing_allowance' => 20000,
                'meal_allowance' => 5000,
                'other_allowance' => 5000,
                'epf_applicable' => true,
                'etf_applicable' => true,
                'overtime_rate_multiplier' => 2.00,
                'holiday_rate_multiplier' => 2.50,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G2',
                'title' => 'Senior Staff',
                'description' => 'Senior Administrators, Supervisors, Team Leaders',
                'min_salary' => 100000,
                'max_salary' => 150000,
                'medical_allowance' => 10000,
                'transport_allowance' => 8000,
                'housing_allowance' => 15000,
                'meal_allowance' => 4000,
                'other_allowance' => 3000,
                'epf_applicable' => true,
                'etf_applicable' => true,
                'overtime_rate_multiplier' => 1.75,
                'holiday_rate_multiplier' => 2.00,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G3',
                'title' => 'Specialist Doctor',
                'description' => 'Consultant Physicians, Surgeons, Specialists',
                'min_salary' => 180000,
                'max_salary' => 350000,
                'medical_allowance' => 20000,
                'transport_allowance' => 15000,
                'housing_allowance' => 25000,
                'meal_allowance' => 5000,
                'other_allowance' => 10000,
                'epf_applicable' => true,
                'etf_applicable' => true,
                'overtime_rate_multiplier' => 2.00,
                'holiday_rate_multiplier' => 2.50,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G4',
                'title' => 'Medical Officer',
                'description' => 'General Practitioners, Resident Doctors',
                'min_salary' => 120000,
                'max_salary' => 200000,
                'medical_allowance' => 12000,
                'transport_allowance' => 10000,
                'housing_allowance' => 18000,
                'meal_allowance' => 4000,
                'other_allowance' => 5000,
                'epf_applicable' => true,
                'etf_applicable' => true,
                'overtime_rate_multiplier' => 1.75,
                'holiday_rate_multiplier' => 2.00,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G5',
                'title' => 'Senior Nurse',
                'description' => 'Nursing Supervisors, Ward Sisters, Matrons',
                'min_salary' => 80000,
                'max_salary' => 120000,
                'medical_allowance' => 10000,
                'transport_allowance' => 8000,
                'housing_allowance' => 12000,
                'meal_allowance' => 3500,
                'other_allowance' => 3000,
                'epf_applicable' => true,
                'etf_applicable' => true,
                'overtime_rate_multiplier' => 1.50,
                'holiday_rate_multiplier' => 2.00,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G6',
                'title' => 'Staff Nurse',
                'description' => 'Registered Nurses, Midwives',
                'min_salary' => 60000,
                'max_salary' => 100000,
                'medical_allowance' => 8000,
                'transport_allowance' => 6000,
                'housing_allowance' => 10000,
                'meal_allowance' => 3000,
                'other_allowance' => 2000,
                'epf_applicable' => true,
                'etf_applicable' => true,
                'overtime_rate_multiplier' => 1.50,
                'holiday_rate_multiplier' => 2.00,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G7',
                'title' => 'Pharmacist',
                'description' => 'Licensed Pharmacists, Pharmacy Managers',
                'min_salary' => 70000,
                'max_salary' => 110000,
                'medical_allowance' => 8000,
                'transport_allowance' => 6000,
                'housing_allowance' => 10000,
                'meal_allowance' => 3000,
                'other_allowance' => 2000,
                'epf_applicable' => true,
                'etf_applicable' => true,
                'overtime_rate_multiplier' => 1.50,
                'holiday_rate_multiplier' => 2.00,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G8',
                'title' => 'Lab Technician',
                'description' => 'Medical Laboratory Technologists, Radiographers',
                'min_salary' => 55000,
                'max_salary' => 90000,
                'medical_allowance' => 7000,
                'transport_allowance' => 5000,
                'housing_allowance' => 8000,
                'meal_allowance' => 2500,
                'other_allowance' => 2000,
                'epf_applicable' => true,
                'etf_applicable' => true,
                'overtime_rate_multiplier' => 1.50,
                'holiday_rate_multiplier' => 2.00,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G9',
                'title' => 'Administrative Staff',
                'description' => 'Receptionists, Cashiers, Clerks, IT Support',
                'min_salary' => 45000,
                'max_salary' => 75000,
                'medical_allowance' => 6000,
                'transport_allowance' => 5000,
                'housing_allowance' => 6000,
                'meal_allowance' => 2000,
                'other_allowance' => 1500,
                'epf_applicable' => true,
                'etf_applicable' => true,
                'overtime_rate_multiplier' => 1.50,
                'holiday_rate_multiplier' => 2.00,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G10',
                'title' => 'Support Staff',
                'description' => 'Center Aids, Cleaning Staff, Security, Helpers',
                'min_salary' => 35000,
                'max_salary' => 55000,
                'medical_allowance' => 5000,
                'transport_allowance' => 4000,
                'housing_allowance' => 5000,
                'meal_allowance' => 2000,
                'other_allowance' => 1000,
                'epf_applicable' => true,
                'etf_applicable' => true,
                'overtime_rate_multiplier' => 1.50,
                'holiday_rate_multiplier' => 2.00,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G11',
                'title' => 'Trainee / Intern',
                'description' => 'Medical Interns, Nursing Trainees, IT Trainees',
                'min_salary' => 25000,
                'max_salary' => 40000,
                'medical_allowance' => 3000,
                'transport_allowance' => 3000,
                'housing_allowance' => 0,
                'meal_allowance' => 2000,
                'other_allowance' => 0,
                'epf_applicable' => false,
                'etf_applicable' => false,
                'overtime_rate_multiplier' => 1.00,
                'holiday_rate_multiplier' => 1.50,
                'status' => 'Active',
            ],
            [
                'grade_code' => 'G12',
                'title' => 'Consultant (Visiting)',
                'description' => 'Visiting Consultants, Part-time Specialists',
                'min_salary' => 200000,
                'max_salary' => 500000,
                'medical_allowance' => 0,
                'transport_allowance' => 20000,
                'housing_allowance' => 0,
                'meal_allowance' => 0,
                'other_allowance' => 15000,
                'epf_applicable' => false,
                'etf_applicable' => false,
                'overtime_rate_multiplier' => 1.00,
                'holiday_rate_multiplier' => 1.00,
                'status' => 'Active',
            ],
        ];

        foreach ($structures as $structure) {
            SalaryStructure::create($structure);
        }

        $this->command->info('Created 12 salary structure grades');
    }
}
