<?php

namespace App\StaticData;

class VariousUsersTableWithField
{
    public static array $usersTableColumns = [
        'users.id',
        'users.first_name',
        'users.last_name',
        'users.email',
        'users.role_as',
    ];
    public static array $usersTableWithField = [
        4 => [
            'table' => 'pharmacists',
            'fields' => [
                'user_id',
                'branch_id',
                'date_of_birth',
                'gender',
                'nic_number',
                'contact_number_mobile',
                'contact_number_landline',
                'email',
                'home_address',
                'emergency_contact_info',
                'photo',
                'nic_photo',
                'pharmacist_registration_number',
                'qualifications',
                'years_of_experience',
                'joining_date',
                'employee_id',
                'contract_type',
                'contract_duration',
                'compensation_package',
                'probation_start_date',
                'probation_end_date',
                'license_validity_date',
                'previous_employment',
            ],
        ],
        3 => [
            'table' => 'cashiers',
            'fields' => [
                'user_id',
                'branch_id',
                'date_of_birth',
                'gender',
                'nic_number',
                'contact_number_mobile',
                'contact_number_landline',
                'email',
                'home_address',
                'emergency_contact_info',
                'photo',
                'nic_photo',
                'qualifications',
                'years_of_experience',
                'joining_date',
                'employee_id',
                'contract_type',
                'contract_duration',
                'compensation_package',
            ],
        ],
        6 => [
            'table' => 'patients',
            'fields' => [
                'branch_id',
                'patient_id',
                'user_id',
                'first_name',
                'last_name',
                'phone',
                'NIC',
                'email',
                'address',
            ],
        ],
        5 => [
            'table' => 'doctors',
            'fields' => [
                'user_id',
                'date_of_birth',
                'gender',
                'nic_number',
                'contact_number_mobile',
                'contact_number_landline',
                'home_address',
                'emergency_contact_info',
                'photo',
                'nic_photo',
                'medical_registration_number',
                'qualifications',
                'years_of_experience',
                'areas_of_specialization',
                'previous_employment',
                'license_validity_date',
                'joining_date',
                'employee_id',
                'contract_type',
                'contract_duration',
                'probation_start_date',
                'probation_end_date',
                'compensation_package',
            ],
        ],
    ];
}
