INSERT IGNORE INTO question_bank (id, category, sub_category, question_text, answer_type, options, is_required, display_order) VALUES
('qb02', 'general_symptoms', 'onset', 'How did the symptoms begin?', 'multiple_choice', '["Sudden","Gradual","After an event","Unknown"]', 0, 2),
('qb03', 'general_symptoms', 'thermal', 'Do you feel generally warm or cold?', 'multiple_choice', '["Warm","Cold","Normal","Variable"]', 0, 3),
('qb04', 'general_symptoms', 'thirst', 'Thirst level?', 'multiple_choice', '["Thirstless","Small sips","Normal","Large quantities","Very thirsty"]', 0, 4),
('qb05', 'general_symptoms', 'perspiration', 'Do you sweat easily?', 'yes_no', NULL, 0, 5),
('qb06', 'general_symptoms', 'sleep', 'Sleep quality (1-10)?', 'scale', NULL, 0, 6),
('qb07', 'general_symptoms', 'appetite', 'How is your appetite?', 'multiple_choice', '["Poor","Normal","Excessive","Variable"]', 0, 7),
('qb08', 'general_symptoms', 'digestion', 'Any digestive complaints?', 'text', NULL, 0, 8),
('qb09', 'mental_state', 'mood', 'Current emotional state?', 'multiple_choice', '["Anxious","Sad","Irritable","Fearful","Calm","Restless","Indifferent"]', 0, 10),
('qb10', 'mental_state', 'stress', 'Stress level (1-10)?', 'scale', NULL, 0, 11),
('qb11', 'mental_state', 'fears', 'Any specific fears or phobias?', 'text', NULL, 0, 12),
('qb12', 'mental_state', 'concentration', 'Any difficulty concentrating?', 'yes_no', NULL, 0, 13),
('qb13', 'mental_state', 'memory', 'Any memory issues?', 'yes_no', NULL, 0, 14),
('qb14', 'physical_symptoms', 'head', 'Any headaches? Describe type and location.', 'text', NULL, 0, 20),
('qb15', 'physical_symptoms', 'respiratory', 'Any respiratory symptoms?', 'text', NULL, 0, 21),
('qb16', 'physical_symptoms', 'musculoskeletal', 'Any joint or muscle pain?', 'text', NULL, 0, 22),
('qb17', 'physical_symptoms', 'skin', 'Any skin conditions?', 'text', NULL, 0, 23),
('qb18', 'physical_symptoms', 'gastric', 'Any stomach or abdomen complaints?', 'text', NULL, 0, 24),
('qb19', 'modalities', 'aggravation', 'What makes symptoms worse?', 'text', NULL, 0, 30),
('qb20', 'modalities', 'amelioration', 'What makes symptoms better?', 'text', NULL, 0, 31),
('qb21', 'modalities', 'time', 'Is there a specific time symptoms worsen?', 'multiple_choice', '["Morning","Afternoon","Evening","Night","No pattern"]', 0, 32),
('qb22', 'modalities', 'weather', 'Do weather changes affect symptoms?', 'multiple_choice', '["Hot weather worse","Cold weather worse","Rainy/damp worse","No effect"]', 0, 33),
('qb23', 'modalities', 'position', 'Does position affect symptoms?', 'multiple_choice', '["Lying down worse","Sitting worse","Standing worse","Motion worse","Rest worse","No effect"]', 0, 34),
('qb24', 'general_symptoms', 'allergies', 'Known allergies?', 'text', NULL, 0, 9),
('qb25', 'general_symptoms', 'medications', 'Current medications?', 'text', NULL, 0, 15),
('qb26', 'general_symptoms', 'surgeries', 'Previous surgeries?', 'text', NULL, 0, 16),
('qb27', 'general_symptoms', 'family', 'Family medical history?', 'text', NULL, 0, 17);
