export const doctorCreateFormInitialState = {
    first_name: "",
    last_name: "",
    password: "",
    date_of_birth: "",
    gender: "",
    nic_number: "",
    contact_number_mobile: "",
    landline_number: "",
    email: "",
    medical_registration_number: "",
    home_address: "",
    emergency_contact_info: "",
    recent_photo: null,
    nic_photo: [null, null],
    medical_reg_number: "",
    qualifications: "",
    years_of_experience: 0,
    specialization: [] as string[],
    work_experience: "",
    working_branch: "",
    license_validity_date: "",
    joining_date: "",
    contact_number_landline: "",
    previous_employment: "",
    probation_start_date: "",
    probation_end_date: "",
    branch_id: "[]",
    employee_id: "",
    contract_type: "",
    contract_duration: "",
    probation_period: { start: "", end: "" },
    compensation_package: "",
};

export const qualificationsOptions: string[] = [
    "Homeopathy Practitioner (HP) / Diploma Holder",
    "BHMS Graduate",
    "MSc in Homeopathy",
    "MD in Homeopathy",
    "PhD in Homeopathy",
    "Specialist Fellowships",
];

export const specializationOptions: { label: string; value: string }[] = [
    { label: "Pediatrics (Child Health)", value: "Pediatrics" },
    {
        label: "Dermatology (Skin, Hair, and Nail Health)",
        value: "Dermatology",
    },
    { label: "Skin Care", value: "Skin Care" },
    { label: "Hair Care", value: "Hair Care" },
    { label: "Nail Health", value: "Nail Health" },
    { label: "Women’s Health and Gynecology", value: "Womens Health" },
    { label: "Geriatrics (Elderly Health)", value: "Geriatrics" },
    { label: "Psychiatry and Mental Health", value: "Psychiatry" },
    { label: "Musculoskeletal Health", value: "Musculoskeletal" },
    { label: "Gastroenterology (Digestive Health)", value: "Gastroenterology" },
    { label: "Respiratory Medicine", value: "Respiratory Medicine" },
    { label: "Endocrinology (Hormonal Health)", value: "Endocrinology" },
    { label: "Cardiology (Heart Health)", value: "Cardiology" },
    { label: "Oncology (Cancer Support)", value: "Oncology" },
    { label: "Immunology and Allergy Management", value: "Immunology" },
    { label: "Addiction and Substance Abuse Treatment", value: "Addiction" },
    { label: "Homeopathic Dentistry", value: "Dentistry" },
    { label: "Neurology (Nervous System Disorders)", value: "Neurology" },
    { label: "Migraines", value: "Migraines" },
    { label: "Epilepsy", value: "Epilepsy" },
    { label: "Parkinson’s", value: "Parkinsons" },
    { label: "Obstetrics and Midwifery", value: "Obstetrics" },
    { label: "Sports Medicine", value: "Sports Medicine" },
    { label: "Urology (Urinary and Reproductive System)", value: "Urology" },
    {
        label: "Homeopathic Surgery (Post-Surgical Recovery Support)",
        value: "Surgery",
    },
    { label: "Rheumatology", value: "Rheumatology" },
    { label: "Infertility and Reproductive Health", value: "Infertility" },
    {
        label: "Chronic Fatigue Syndrome and Fibromyalgia",
        value: "Chronic Fatigue",
    },
    { label: "Environmental Medicine", value: "Environmental Medicine" },
    { label: "Chronic Inflammatory Response Syndrome (CIRS)", value: "CIRS" },
    { label: "Electromagnetic Hypersensitivity Syndrome (EHS)", value: "EHS" },
    { label: "Aesthetic Homeopathy", value: "Aesthetic Homeopathy" },
    { label: "Therapy", value: "Therapy" },
];

export const workingBranches: {
    branch_id: number;
    branch_location: string;
    symbol: string;
}[] = [
    { branch_id: 1, branch_location: "Kurunegala", symbol: "267" },
    { branch_id: 2, branch_location: "Rambukkana", symbol: "38" },
    { branch_id: 3, branch_location: "Ratmalana", symbol: "158" },
    { branch_id: 4, branch_location: "Rathnapura", symbol: "192" },
];
