export const nurse_create_form_initial_state = {
    full_name: "",
    date_of_birth: "",
    gender: "",
    nic_or_passport: "",
    mobile_number: "",
    landline_number: "",
    email: "",
    home_address: "",
    emergency_contact: "",
    recent_photo: null,
    nursing_reg_number: "",
    qualifications: "",
    years_of_experience: 0,
    specialization: "",
    work_experience: "",
    nurse_training_certifications: "",
    license_validity_date: "",
    additional_certifications: "",
    joining_date: "",
    employee_id: "",
    contract_type: "",
    contract_duration: "",
    probation_period: { start: "", end: "" },
    compensation_package: "",
};
