"""Initial_migration

Revision ID: 162cb8e5c9d2
Revises:
Create Date: 2026-01-30 07:07:13.817442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '162cb8e5c9d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('center_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('register_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('center_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('division', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('division_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('register_document', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('register_number')
    )
    op.create_index(op.f('ix_branch_center_name'), 'branch', ['center_name'], unique=True)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_as', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_branch_center_name'), table_name='branch')
    op.drop_table('branch')
    # ### end Alembic commands ###
