"""add name to doctor

Revision ID: 52a1b9c3d4e8
Revises: 904ad58a2077
Create Date: 2024-02-08 11:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '52a1b9c3d4e8'
down_revision = '904ad58a2077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('first_name', sa.String(255), nullable=True))
    op.add_column('doctor', sa.Column('last_name', sa.String(255), nullable=True))
    
    # Update existing records to have a default value or copy from user table if possible
    # For now, we will just set them to empty string or nullable=True first, then update, then nullable=False
    # But for simplicity in this dev env, I'll direct set them to nullable=False with a server_default
    
    # Actually, let's keep it nullable=True for now to avoid issues with existing data if any, 
    # but the model says they are required.
    # Let's try to update them from user table if possible, or just set default.
    op.execute("UPDATE doctor SET first_name = 'Unknown', last_name = 'Doctor' WHERE first_name IS NULL")
    
    # Now alter to not null
    op.alter_column('doctor', 'first_name', existing_type=sa.String(255), nullable=False)
    op.alter_column('doctor', 'last_name', existing_type=sa.String(255), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'last_name')
    op.drop_column('doctor', 'first_name')
    # ### end Alembic commands ###
