"""Add_Doctor_Patient_tables

Revision ID: 9507efed4a4b
Revises: 162cb8e5c9d2
Create Date: 2026-01-30 07:13:10.460116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9507efed4a4b'
down_revision: Union[str, None] = '162cb8e5c9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qualification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('patient',
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blood_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emergency_contact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('doctor')
    # ### end Alembic commands ###
