"""Refactor Branch and Pharmacy models

Revision ID: d2f8a1a84e31
Revises: 314b64530b38
Create Date: 2026-02-08 08:12:21.306509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd2f8a1a84e31'
down_revision: Union[str, None] = '314b64530b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('appointment', ...) removed to avoid FK issues
    
    op.add_column('branch', sa.Column('branch_admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.alter_column('branch', 'id', ...) removed
    op.create_foreign_key(None, 'branch', 'user', ['branch_admin_id'], ['id'])
    
    # op.alter_column('doctor', ...) removed
    # op.alter_column('patient', ...) removed
    
    # Pharmacist changes
    # op.alter_column('pharmacist', 'id', ...) removed
    # op.alter_column('pharmacist', 'user_id', ...) removed
    
    op.drop_constraint(op.f('pharmacist_ibfk_1'), 'pharmacist', type_='foreignkey')
    op.drop_column('pharmacist', 'branch_id')
    
    # Pharmacy changes
    # op.alter_column('pharmacy', 'pharmacist_id', ...) removed
    
    op.drop_constraint(op.f('pharmacy_ibfk_1'), 'pharmacy', type_='foreignkey')
    op.drop_column('pharmacy', 'branch_id')
    
    # op.alter_column('queue', ...) removed
    # op.alter_column('user', ...) removed
    # op.alter_column('visit', ...) removed


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visit', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('visit', 'appointment_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('visit', 'branch_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('visit', 'doctor_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('visit', 'patient_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('queue', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('queue', 'branch_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('queue', 'doctor_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('queue', 'patient_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.add_column('pharmacy', sa.Column('branch_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('pharmacy_ibfk_1'), 'pharmacy', 'branch', ['branch_id'], ['id'])
    op.alter_column('pharmacy', 'pharmacist_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.add_column('pharmacist', sa.Column('branch_id', mysql.VARCHAR(length=36), nullable=False))
    op.create_foreign_key(op.f('pharmacist_ibfk_1'), 'pharmacist', 'branch', ['branch_id'], ['id'])
    op.alter_column('pharmacist', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('pharmacist', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('patient', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('patient', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('doctor', 'branch_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('doctor', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('doctor', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.alter_column('branch', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('branch', 'branch_admin_id')
    op.alter_column('appointment', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('appointment', 'branch_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('appointment', 'doctor_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('appointment', 'patient_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
