export const createFormSubmitData = (productData: any, data: any) => {
    return {
        item_code: productData.product_details.sku,
        item_name: productData.product_details.name,
        barcode: productData.product_details.barcode,
        generic_name: productData.product_details.genericName,
        brand_name: productData.product_details.brandName,
        category: productData.product_details.category,
        unit: productData.product_details.units,
        supplier_id: productData.suppliers.selectedSupplierId?.supplier_id,
        warranty_serial: productData.warranty.warrantySerial,
        warranty_duration: productData.warranty.warrantyDuration,
        warranty_start_date: productData.warranty.warrantyStartDate,
        warranty_end_date: productData.warranty.warrantyExpirationDate,
        warranty_type: productData.warranty.warrantyType,
        current_stock: data.quantityInStock,
        min_stock: data.minimumStockLevel,
        reorder_level: data.reorderLevel,
        reorder_quantity: data.reorderQuantity,
        unit_cost: data.unitCost,
        unit_selling_price: data.sellingPrice,
        expiry_date: data.expiryDate,
        entry_date: data.dateOfEntry,
        stock_status: data.stockStatus,
        product_store_location: data.product_store_location,
        stock_update_date: data.stockUpdateDate,
        damaged_stock: data.damagedStock,
    };
};
